Repository Manish-Kumar-Vats/Delhi-Tour-App, pull requests merged in 2020-10, with the labels that each got.

#1 Update activity_detailed_place.xml
  app/src/main/res/layout/activity_detailed_place.xml
Labels: Hacktoberfest, Hacktoberfest-accepted

#2 Update EatAndDrinksActivity.java
  app/src/main/java/android/example/tourguideapp/EatAndDrinksActivity.java
Labels: Hacktoberfest, Hacktoberfest-accepted, enhancement

#3 Update activity_detailed_place.xml
  app/src/main/res/layout/activity_detailed_place.xml
Labels: Hacktoberfest, Hacktoberfest-accepted

#4 Update README.md
  README.md
Labels: Hacktoberfest, Hacktoberfest-accepted, documentation
